### PR TITLE
Add Head block and GTM

### PR DESCRIPTION
**Pull request by gkorland**

### CODE REVIEW

**Comment by gkorland** [comment]
yes, it seems like it overridden the all `<head>`

**Comment by gkorland** [comment]
@itamarhaber I know it's not pretty but I didn't find another way

**Comment by itamarhaber** [comment]
This is less "not pretty": https://github.com/RedisLabs/engineering-blog/tree/gtm

**Comment by gkorland** [comment]
whatever works for you...

**Pull request closed without merging**
